### PR TITLE
Fix integration tests

### PR DESCRIPTION
**Pull request by mveytsman**

### CODE REVIEW

**Comment by phillmv** [comment]
Ugh, CircleCI no longer supports go 1.4. Jerks.

**Comment by mveytsman** [comment]
I think they just don't support the "go" directive?

--
Max Veytsman
Co-founder appcanary.com
@mveytsman <https://twitter.com/mveytsman>

**Comment by phillmv** [comment]
Ah, no, you didn't bother to pull from master prior to making this branch :\.

**Comment by phillmv** [comment]
Good bye

**Pull request closed without merging**
