### PR TITLE
Touch and chown /var/log/appcanary.log

### LINKED ISSUE #85: get it to work without sudo
@MacLeodMike doesn't this come down to permissions to write to /var/log/appcanary.log ?

### PR DESCRIPTION
**Pull request by MacLeodMike**
Should resolve #85

### CODE REVIEW

**Comment by phillmv** [comment]
Do you understand how test/pkg works to add this as a test there?

**Comment by MacLeodMike** [comment]
I still get a big ol' fail when trying 'rake integration:everything'. There must be something missing from my environment, but I'm not sure what.

**Comment by MacLeodMike** [comment]
I pulled the logfile from CONFIG_FILES, and we're now depending on the post-install.sh to create it. I think this is preferable - log files really aren't the same as log files, and the same logic should not be applied. For example, when upgrading the package I shouldn't be prompted whether to install the new logfile from the maintainer.

On a practical level, when it was created via CONFIG_FILES it would always be set to root:root, after the post-install.sh ran.

**Comment by phillmv** [comment]
The test should also confirm that the right perms got set :). 

Also do the tests pass? You didn't increment the OKAC counter so these should all fail no?

**Comment by phillmv** [comment]
This *is* good and technically correct but not an answer for #85 ;). I think that'll have to be a code change.

**Pull request merged**
