### PR TITLE
Logrotate

### LINKED ISSUE #84: logrotate
please, i beg of you

### PR DESCRIPTION
**Pull request by MacLeodMike**
Resolves #84

### CODE REVIEW

**Comment by phillmv** [comment]
Why restart the service on log rotate?

**Comment by MacLeodMike** [comment]
If you don't maintain the file socket then we don't have to. But not knowing whether you do or not, this was the safer approach. If you keep the socket open when the file is rotated you'll continue to write to the old file.

We should also know how often you want to rotate. I set it for weekly, but I don't know how much the agent actually logs in general use.

**Comment by phillmv** [comment]
How many logs does this keep? Or is it just rotating them without deleting the old ones?

**Comment by MacLeodMike** [comment]
Rotate once a week, and keep four weeks of data. It compresses rotated files.

Would you prefer to rotate daily and keep seven? That's the other common setting.

Do you open a new filehandle each time you write to log? If so I can remove the restart. Alternatively, it's also common practice for long running processes to react to HUP by rereading config files and closing/recreating file handles. If you do that then I can do that instead.

**Comment by phillmv** [comment]
Pretty sure we don't so a restart for now will do. 

Be cool to trigger writing to the log and testing that also.

**Pull request merged**
